# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
workspace 'xnbMall'


project 'ShopKeeper/ShopKeeper.xcodeproj'

target 'ShopKeeper' do
	pod 'AFNetworking'
	pod 'MBProgressHUD', '~>1.0.0'
	pod 'Reachability'
	pod 'Masonry'
	pod 'BlocksKit'
	pod 'SVProgressHUD'
	pod 'MJRefresh'
	pod 'SDWebImage'
	pod 'DateTools'
    pod 'TYAlertController'
    pod 'YCXMenu'
    pod 'MWPhotoBrowser'
    pod 'SDCycleScrollView'
    pod 'FMDB'
    pod 'MJExtension'
    #pod 'YYKit'
    pod 'YYCache'
    pod 'YYModel'
    pod 'SRMModalViewController'
    pod 'JSONModel'
    pod 'ActionSheetPicker-3.0'
	project 'ShopKeeper/ShopKeeper.xcodeproj'
end


